[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_gallery = "HAye5oF3GyRcsWRUfZireXMxHSjJFtGhtbwN86wLLxJE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/school-of-solana/dev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
